sudo: require
language: cpp
compiler:
    - gcc
    - clang
dist: trusty
cache: apt
os: linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-r-test

before_install:
    - sudo apt-get update -q
    - sudo apt-get install clang-6.0 gcc-7 g++-7 -y
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} ; cd ${DEPS_DIR}
    - |
      CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --quiet --no-check-certificate  -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DCMAKE_CXX_STANDARD=14 ..

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd build
    - cmake --build .
    - cmake --build . --target check
